# stable
edition                  = "2021"
reorder_imports          = true
use_field_init_shorthand = true
use_small_heuristics     = "Max"
use_try_shorthand        = true

# unstable
unstable_features = true
# version           = "Two"

condense_wildcard_suffixes  = true
fn_single_line              = true
format_code_in_doc_comments = true
format_macro_matchers       = true
format_strings              = true
imports_granularity         = "Crate"
imports_layout              = "Mixed"
newline_style               = "Unix"
normalize_comments          = true
normalize_doc_attributes    = true
overflow_delimited_expr     = true
reorder_impl_items          = true
group_imports               = "StdExternalCrate"
wrap_comments               = true
