{{- if not .Values.serviceAccount.name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "solana-tx-p2p-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "solana-tx-p2p-server.serviceAccount.name" . }}
{{- end }}
