apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "zta-iam.labels" . | nindent 4 }}
  name: {{ include "zta-iam.fullname" . }}
type: Opaque
stringData:
  ZTA_IAM_POSTGRES_HOST: {{ quote .Values.postgres.host }}
  ZTA_IAM_POSTGRES_PORT: {{ quote .Values.postgres.port }}
  ZTA_IAM_POSTGRES_USER: {{ quote .Values.postgres.user }}
  ZTA_IAM_POSTGRES_PASSWORD: {{ quote .Values.postgres.password }}
  ZTA_IAM_POSTGRES_DATABASE: {{ quote .Values.postgres.database }}

  ZTA_IAM_KEYCLOAK_CLIENT_SECRET: {{ quote .Values.keycloak.clientSecret }}
  ZTA_IAM_KEYCLOAK_CLIENT_SECRET_MAP: {{ quote .Values.keycloak.clientSecretMap }}

  ZTA_IAM_APPLICATION_PRIVATE_KEY: {{ quote .Values.applicationPrivateKey }}

  ZTA_IAM_CARD_IDP_CLIENT_SECRET: {{ quote .Values.cardIdp.clientSecret }}

  ZTA_IAM_TLS_KEY: {{ quote .Values.tlsKey }}
