name: Integration

on:
  pull_request:
    paths:
      - .cargo/**
      - .dockerignore
      - .github/**
      - dev-support/containers/**
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - crates/**
      - iam/**
      - rust-toolchain.toml
      - rustfmt.toml
  push:
    branches:
      - main
      - develop
      - release/**
      - hotfix/**
      - feature/**
      - ci/**

concurrency:
  group: integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    name: Build and publish images
    uses: ./.github/workflows/build-image.yaml
    secrets: inherit
    with:
      platforms: linux/amd64
# TODO integration test using image
